import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the local connector build and should not be linted as
    // application source. These folders are recreated by WXT/Next builds.
    "apps/keeprone-connect/.wxt/**",
    "apps/keeprone-connect/.output/**",
    ".output/**",
    // Local git worktrees (see .gitignore) are separate checkouts with their own
    // .next builds; the patterns above are anchored and don't reach nested paths.
    ".worktrees/**",
  ]),
]);

export default eslintConfig;
